---
title: "Assignment 2 PS2"
author: "Anne Schwenker"
date: "February 6, 2019"
output: html_document
---
2. Problem set 2
Matrix factorization is a very important problem. There are supercomputers built just
to do matrix factorizations. Every second you are on an airplane, matrices are being
factorized. Radars that track flights use a technique called Kalman filtering. At the heart
of Kalman Filtering is a Matrix Factorization operation. Kalman Filters are solving linear
systems of equations when they track your flight using radars.
Write an R function to factorize a square matrix A into LU or LDU, whichever you
prefer. 

```{r}
library(matrixcalc)
MFO<-function(A){
  diagA<-diag(A)
  if(is.square.matrix(A) && diagA[1]==1 && unique(diagA)==1){
    for (i in 2:nrow(A)){
      print(paste("iteration",i))
      for (j in (i+1):nrow(A)-2){
        print(paste("iteration",j))
        print(A[i,j])
        a<-A[i-1,j]
        print(a)
        b<-A[i,j]
        print(b)
        multiplier<--1*b/a
        print(multiplier)
        # create L based on matrix to fill in lower with multipliers
        print(A[i,])
        A[i,]=((A[i,]*multiplier)+A[i,])
        print(A[i,])
          }
    }
    print(A)
      }else {
print("Matrix is not square")
      }
}
A<-matrix(c(1,2,4,0,1,3,0,0,1),nrow = 3, ncol = 3)
MFO(A)
print(A)
print("tried")
AM<-matrix(c(1,2,4,0,1,3,0,0,1),nrow = 3, ncol = 3)

luA <- lu.decomposition( AM )
L <- luA$L
U <- luA$U
print( L )
print( U )

identical(U, AAt) 

```


You don’t have to worry about permuting rows of A and you can assume that A is less
than 5x5, if you need to hard-code any variables in your code. If you doing the entire
assignment in R, then please submit only one markdown document for both the problems.